### PR TITLE
refactor: use-template-literals: reuse isStringLiteral

### PR DESCRIPTION
**Pull request by coderaiser**
#### 📚 Description

Reused `isStringLiteral`

### CODE REVIEW

**Comment by mohab-sameh** [comment]
@coderaiser can you please sign the CLA so that merging is unblocked?

**Comment by alexbit-codemod** [comment]
a true codemod champ! @coderaiser ! THANK YOU.

**Review by arybitskiy — APPROVED** [review]

**Comment by mohab-sameh** [comment]
@mirai2k linting ci/cd is failing here. Can you please check. If it's a false positive related to env vars blocking building let me know so I can merge.

**Comment by mirai2k** [comment]
@mohab-sameh this is looks good, im pretty sure that you can merge it

**Pull request merged**
