### PR TITLE
migrate to pnpm v9.5.0 and adopt the "catalog" feature

### PR DESCRIPTION
**Pull request by arybitskiy**
Migrate to pnpm v9.5.0 and adopt catalog for Codemod monorepo.

This PR contains safe changes only. 
Next PR will contain potentially unsafe ones that require more testing and review.

The following packages were not selected to move to the catalog, because they have multiple versions in the workspace:
fp-ts (^2.15.0, ^2.14.0)
semver (^7.3.8, ^7.6.2, 7.6.0)
ts-morph (^19.0.0, 18.0.0, ^22.0.0)
@types/node (18.11.18, 20.10.5, 18.11.9, 20.10.3, 20.8.5, ^16.18.21, 20.9.0, ^20.12.3)
@types/semver (^7.3.13, ^7.5.8, 7.5.8)
esbuild (^0.17.18, ^0.19.12, ^0.21.1, ^0.23.0, ^0.17.14, 0.19.5)
ts-node (^10.9.1, 10.9.2, ^10.9.2, 10.9.1)
typescript (5.1.6, ^5.2.2, ^4.9.5, 5.2.2)
nodemon (3.0.2, ^2.0.15)
tsx (^4.7.1, ^4.11.0)
ai (2.2.29, ^2.1.32)
@babel/parser (^7.21.1, ^7.24.4)
@babel/preset-env (^7.1.6, ^7.24.1)
@babel/types (7.21.2, ^7.24.0)
@monaco-editor/react (^4.4.6, ^4.5.0)
@types/jscodeshift (^0.11.6, ^0.11.11, ^0.11.10)
classnames (2.5.1, ^2.3.2)
jscodeshift (^0.15.0, ^0.15.1, ^0.15.2, ^0.16.1, 0.14.0)
monaco-editor (^0.36.1, ^0.37.1)
prettier (^2.8.8, 3.2.5, ^3.2.5)
react (18.2.0, ^18.2.0)
react-dom (18.2.0, ^18.2.0)
react-resizable-panels (^2.0.15, ^0.0.51)
@babel/core (^7.21.0, ^7.24.4)
@types/react (18.2.55, ^18.0.30)
memfs (^4.6.0, ^4.8.2)
vitest (^1.0.1, 1.1.0)
tar (^6.2.0, ^6.1.15)

### CODE REVIEW

**Review by r4zendev — APPROVED** [review]
looks fine, but i'm not sure if we actually need it. we need to test building and booting up the projects.

**Review by alexbit-codemod — CHANGES_REQUESTED** [review]
lets have two PRs, one for safe and one for possible unsafe changes.

**Comment by arybitskiy** [comment]
> lets have two PRs, one for safe and one for possible unsafe changes.

added only safe changes to this PR

**Comment by alexbit-codemod** [comment]
epic. lgtm. lfg. @arybitskiy

**Review by alexbit-codemod — APPROVED** [review]

**Pull request merged**
