### PR TITLE
feat(Codemod)  : Preact Migrations vX

### PR DESCRIPTION
**Pull request by manishjha-04**
#### 📚This codemod automates the migration process from Preact versions earlier than 8 to the latest version (vX), ensuring compatibility and streamlining the upgrade.

- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by mohab-sameh** [comment]
@all-contributors add @manishjha-04 for code

**Comment by manishjha-04** [comment]
Yeah Hii @mohab-sameh 


 I do have a couple of repositories you can check out: [Nectarine](https://github.com/developit/nectarine) and [Spotifio-UI](https://github.com/samgrulich/spotifio-ui). Depending on the code, you might find that different codemods are needed for each.

 You can use the migration recipe codemod `preact/X/migration-recipe` on them, as the required updates may vary for each.

**Comment by arshcodemod** [comment]
Great work Manish, have you tested on these repos already?

**Comment by manishjha-04** [comment]
Yup @arshcodemod !

**Pull request closed without merging**
