### PR TITLE
[docs] fix: typo

### PR DESCRIPTION
**Pull request by morinokami**

### CODE REVIEW

**Review by mohab-sameh — APPROVED** [review]
Thanks @morinokami!

**Comment by mohab-sameh** [comment]
@all-contributors add @morinokami for docs

**Comment by r4zendev** [comment]
This note should probably be removed altogether, we are not looking for a global installation anymore and just install `esbuild` as a dependency via npm native behaviour. Thanks for noticing this one though.

**Comment by mohab-sameh** [comment]
@r4zendev Alright. I removed it for now. If we revert this behavior, just let me know and I'll revert back.

**Comment by mohab-sameh** [comment]
@mirai2k something is failing with backend env variables. Can you check this please?

**Pull request merged**
