### PR TITLE
Add basic support for multiple tabs

### PR DESCRIPTION
**Pull request by mohebifar**
**Please check if the PR fulfills these requirements**:

-   [ ] The commit message follows [our code of conduct](https://github.com/codemod-com/codemod-registry/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/codemod-com/codemod-registry/blob/main/CONTRIBUTING.md)
-   [ ] Tests for the changes have been added (for bug fixes/features)
-   [ ] Docs have been added / updated (for bug fixes / features)

**Please include the following information in your pull request**:

-   **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

-   **What is the current behavior?** (You can also link to an open issue here)

-   **What is the new behavior (if this is a feature change)?**

-   **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

-   **Any other information (if needed)**:

### CODE REVIEW

**Comment by hbjORbj** [comment]
Thanks for opening the PR! Can you resolve the merge conflicts?

**Comment by mohab-sameh** [comment]
@all-contributors add @mohebifar for code and bug fixes

**Comment by alexbit-codemod** [comment]
stale. closing this out.

**Comment by alexbit-codemod** [comment]
@grzim will take care of this feature. thanks mo for the work here. hope to see your future contributions soon. cheer.

**Pull request closed without merging**
